CREATE TABLE IF NOT EXISTS inventory_adjustments (
    adjustment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INT NOT NULL REFERENCES stores (store_id),
    inventory_id INT NOT NULL REFERENCES inventory (inventory_id),
    product_id INT NOT NULL REFERENCES products (product_id),
    previous_qty INT NOT NULL DEFAULT 0,
    adjusted_qty INT NOT NULL,
    reason TEXT DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_by INT NOT NULL REFERENCES employees (employee_id),
    reviewed_by INT REFERENCES employees (employee_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_inventory_adjustments_store_status ON inventory_adjustments (store_id, status);
