-- Completely wipes all data from the database and restarts IDs
TRUNCATE TABLE 
    categories,
    suppliers,
    products,
    product_suppliers,
    mims_location,
    inventory,
    mims_location_items,
    out_of_stock_log,
    fill_reports,
    fill_report_items,
    price_tag_jobs,
    price_tag_job_items,
    transactions,
    transaction_items,
    online_orders,
    online_order_items,
    cycle_counts,
    cycle_count_items,
    inventory_transactions,
    audit_log,
    preferred_members,
    purchase_orders,
    purchase_orders_items,
    purchase_order_lprs,
    purchase_order_lpr_items,
    stock_transfers,
    stock_transfer_items,
    mims_scan_log
RESTART IDENTITY CASCADE;
