INSERT INTO categories (name) VALUES
('Category 1'),
('Category 2'),
('Category 3'),
('Category 4'),
('Category 5'),
('Category 6'),
('Category 7'),
('Category 8'),
('Category 9'),
('Category 10'),
('Category 11'),
('Category 12'),
('Category 13'),
('Category 14'),
('Category 15');
