// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces.go -destination=internal/service/mocks/mock_repositories.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "radius/internal/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockEmployeeRepository is a mock of EmployeeRepository interface.
type MockEmployeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeRepositoryMockRecorder
	isgomock struct{}
}

// MockEmployeeRepositoryMockRecorder is the mock recorder for MockEmployeeRepository.
type MockEmployeeRepositoryMockRecorder struct {
	mock *MockEmployeeRepository
}

// NewMockEmployeeRepository creates a new mock instance.
func NewMockEmployeeRepository(ctrl *gomock.Controller) *MockEmployeeRepository {
	mock := &MockEmployeeRepository{ctrl: ctrl}
	mock.recorder = &MockEmployeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployeeRepository) EXPECT() *MockEmployeeRepositoryMockRecorder {
	return m.recorder
}

// ActivateEmployeeById mocks base method.
func (m *MockEmployeeRepository) ActivateEmployeeById(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateEmployeeById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateEmployeeById indicates an expected call of ActivateEmployeeById.
func (mr *MockEmployeeRepositoryMockRecorder) ActivateEmployeeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateEmployeeById", reflect.TypeOf((*MockEmployeeRepository)(nil).ActivateEmployeeById), ctx, id)
}

// CreateEmployee mocks base method.
func (m *MockEmployeeRepository) CreateEmployee(ctx context.Context, model models.CreateEmployeeRow) (*models.CreateEmployeeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, model)
	ret0, _ := ret[0].(*models.CreateEmployeeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockEmployeeRepositoryMockRecorder) CreateEmployee(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockEmployeeRepository)(nil).CreateEmployee), ctx, model)
}

// GetAllEmployees mocks base method.
func (m *MockEmployeeRepository) GetAllEmployees(ctx context.Context, limit, offset int, storeId *int) ([]models.Employee, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEmployees", ctx, limit, offset, storeId)
	ret0, _ := ret[0].([]models.Employee)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllEmployees indicates an expected call of GetAllEmployees.
func (mr *MockEmployeeRepositoryMockRecorder) GetAllEmployees(ctx, limit, offset, storeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEmployees", reflect.TypeOf((*MockEmployeeRepository)(nil).GetAllEmployees), ctx, limit, offset, storeId)
}

// GetEmployeeByEmail mocks base method.
func (m *MockEmployeeRepository) GetEmployeeByEmail(ctx context.Context, email string) (*models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByEmail", ctx, email)
	ret0, _ := ret[0].(*models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByEmail indicates an expected call of GetEmployeeByEmail.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeeByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByEmail", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeeByEmail), ctx, email)
}

// GetEmployeeByEmailWithSession mocks base method.
func (m *MockEmployeeRepository) GetEmployeeByEmailWithSession(ctx context.Context, email string) (*models.GetEmployeeByEmailWithSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByEmailWithSession", ctx, email)
	ret0, _ := ret[0].(*models.GetEmployeeByEmailWithSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByEmailWithSession indicates an expected call of GetEmployeeByEmailWithSession.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeeByEmailWithSession(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByEmailWithSession", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeeByEmailWithSession), ctx, email)
}

// TerminateEmployeeById mocks base method.
func (m *MockEmployeeRepository) TerminateEmployeeById(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateEmployeeById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateEmployeeById indicates an expected call of TerminateEmployeeById.
func (mr *MockEmployeeRepositoryMockRecorder) TerminateEmployeeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateEmployeeById", reflect.TypeOf((*MockEmployeeRepository)(nil).TerminateEmployeeById), ctx, id)
}

// UpdateEmployee mocks base method.
func (m *MockEmployeeRepository) UpdateEmployee(ctx context.Context, body models.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", ctx, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockEmployeeRepositoryMockRecorder) UpdateEmployee(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockEmployeeRepository)(nil).UpdateEmployee), ctx, body)
}

// MockStoreRepository is a mock of StoreRepository interface.
type MockStoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreRepositoryMockRecorder is the mock recorder for MockStoreRepository.
type MockStoreRepositoryMockRecorder struct {
	mock *MockStoreRepository
}

// NewMockStoreRepository creates a new mock instance.
func NewMockStoreRepository(ctrl *gomock.Controller) *MockStoreRepository {
	mock := &MockStoreRepository{ctrl: ctrl}
	mock.recorder = &MockStoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreRepository) EXPECT() *MockStoreRepositoryMockRecorder {
	return m.recorder
}

// ActivateStore mocks base method.
func (m *MockStoreRepository) ActivateStore(ctx context.Context, storeId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateStore", ctx, storeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateStore indicates an expected call of ActivateStore.
func (mr *MockStoreRepositoryMockRecorder) ActivateStore(ctx, storeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateStore", reflect.TypeOf((*MockStoreRepository)(nil).ActivateStore), ctx, storeId)
}

// CreateStore mocks base method.
func (m *MockStoreRepository) CreateStore(ctx context.Context, body models.CreateStoreRequest) (*models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", ctx, body)
	ret0, _ := ret[0].(*models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockStoreRepositoryMockRecorder) CreateStore(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockStoreRepository)(nil).CreateStore), ctx, body)
}

// DeactivateStore mocks base method.
func (m *MockStoreRepository) DeactivateStore(ctx context.Context, storeId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateStore", ctx, storeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateStore indicates an expected call of DeactivateStore.
func (mr *MockStoreRepositoryMockRecorder) DeactivateStore(ctx, storeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateStore", reflect.TypeOf((*MockStoreRepository)(nil).DeactivateStore), ctx, storeId)
}

// GetAllStores mocks base method.
func (m *MockStoreRepository) GetAllStores(ctx context.Context, pageSize, pageNumber int) ([]models.Store, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStores", ctx, pageSize, pageNumber)
	ret0, _ := ret[0].([]models.Store)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllStores indicates an expected call of GetAllStores.
func (mr *MockStoreRepositoryMockRecorder) GetAllStores(ctx, pageSize, pageNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStores", reflect.TypeOf((*MockStoreRepository)(nil).GetAllStores), ctx, pageSize, pageNumber)
}

// GetStore mocks base method.
func (m *MockStoreRepository) GetStore(ctx context.Context, storeId int) (*models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", ctx, storeId)
	ret0, _ := ret[0].(*models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockStoreRepositoryMockRecorder) GetStore(ctx, storeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockStoreRepository)(nil).GetStore), ctx, storeId)
}

// UpdateStore mocks base method.
func (m *MockStoreRepository) UpdateStore(ctx context.Context, body models.UpdateStoreRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStore", ctx, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStore indicates an expected call of UpdateStore.
func (mr *MockStoreRepositoryMockRecorder) UpdateStore(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStore", reflect.TypeOf((*MockStoreRepository)(nil).UpdateStore), ctx, body)
}

// MockSalesRepository is a mock of SalesRepository interface.
type MockSalesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSalesRepositoryMockRecorder
	isgomock struct{}
}

// MockSalesRepositoryMockRecorder is the mock recorder for MockSalesRepository.
type MockSalesRepositoryMockRecorder struct {
	mock *MockSalesRepository
}

// NewMockSalesRepository creates a new mock instance.
func NewMockSalesRepository(ctrl *gomock.Controller) *MockSalesRepository {
	mock := &MockSalesRepository{ctrl: ctrl}
	mock.recorder = &MockSalesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSalesRepository) EXPECT() *MockSalesRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockSalesRepository) CreateTransaction(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateTransaction", ctx)
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockSalesRepositoryMockRecorder) CreateTransaction(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockSalesRepository)(nil).CreateTransaction), ctx)
}

// GetAllTransactions mocks base method.
func (m *MockSalesRepository) GetAllTransactions(ctx context.Context, limit, offset int, storeID *int) ([]models.Transaction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTransactions", ctx, limit, offset, storeID)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllTransactions indicates an expected call of GetAllTransactions.
func (mr *MockSalesRepositoryMockRecorder) GetAllTransactions(ctx, limit, offset, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTransactions", reflect.TypeOf((*MockSalesRepository)(nil).GetAllTransactions), ctx, limit, offset, storeID)
}

// GetProductTransactions mocks base method.
func (m *MockSalesRepository) GetProductTransactions(ctx context.Context, sku int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetProductTransactions", ctx, sku)
}

// GetProductTransactions indicates an expected call of GetProductTransactions.
func (mr *MockSalesRepositoryMockRecorder) GetProductTransactions(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductTransactions", reflect.TypeOf((*MockSalesRepository)(nil).GetProductTransactions), ctx, sku)
}

// GetTransactionByID mocks base method.
func (m *MockSalesRepository) GetTransactionByID(ctx context.Context, id int, storeID *int) (*models.Transaction, []models.TransactionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", ctx, id, storeID)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].([]models.TransactionItem)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockSalesRepositoryMockRecorder) GetTransactionByID(ctx, id, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockSalesRepository)(nil).GetTransactionByID), ctx, id, storeID)
}

// MockOrdersRepository is a mock of OrdersRepository interface.
type MockOrdersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersRepositoryMockRecorder
	isgomock struct{}
}

// MockOrdersRepositoryMockRecorder is the mock recorder for MockOrdersRepository.
type MockOrdersRepositoryMockRecorder struct {
	mock *MockOrdersRepository
}

// NewMockOrdersRepository creates a new mock instance.
func NewMockOrdersRepository(ctrl *gomock.Controller) *MockOrdersRepository {
	mock := &MockOrdersRepository{ctrl: ctrl}
	mock.recorder = &MockOrdersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepository) EXPECT() *MockOrdersRepositoryMockRecorder {
	return m.recorder
}

// GetAllOnlineOrders mocks base method.
func (m *MockOrdersRepository) GetAllOnlineOrders(ctx context.Context, limit, offset int, storeID *int) ([]models.OnlineOrder, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOnlineOrders", ctx, limit, offset, storeID)
	ret0, _ := ret[0].([]models.OnlineOrder)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllOnlineOrders indicates an expected call of GetAllOnlineOrders.
func (mr *MockOrdersRepositoryMockRecorder) GetAllOnlineOrders(ctx, limit, offset, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOnlineOrders", reflect.TypeOf((*MockOrdersRepository)(nil).GetAllOnlineOrders), ctx, limit, offset, storeID)
}

// GetOnlineOrderByID mocks base method.
func (m *MockOrdersRepository) GetOnlineOrderByID(ctx context.Context, id int, storeID *int) (*models.OnlineOrder, []models.OnlineOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnlineOrderByID", ctx, id, storeID)
	ret0, _ := ret[0].(*models.OnlineOrder)
	ret1, _ := ret[1].([]models.OnlineOrderItem)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOnlineOrderByID indicates an expected call of GetOnlineOrderByID.
func (mr *MockOrdersRepositoryMockRecorder) GetOnlineOrderByID(ctx, id, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnlineOrderByID", reflect.TypeOf((*MockOrdersRepository)(nil).GetOnlineOrderByID), ctx, id, storeID)
}

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// CreateInventoryItem mocks base method.
func (m *MockInventoryRepository) CreateInventoryItem(ctx context.Context, model models.Inventory) (*models.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInventoryItem", ctx, model)
	ret0, _ := ret[0].(*models.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInventoryItem indicates an expected call of CreateInventoryItem.
func (mr *MockInventoryRepositoryMockRecorder) CreateInventoryItem(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInventoryItem", reflect.TypeOf((*MockInventoryRepository)(nil).CreateInventoryItem), ctx, model)
}

// DeleteProductBySku mocks base method.
func (m *MockInventoryRepository) DeleteProductBySku(ctx context.Context, sku int) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductBySku", ctx, sku)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProductBySku indicates an expected call of DeleteProductBySku.
func (mr *MockInventoryRepositoryMockRecorder) DeleteProductBySku(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductBySku", reflect.TypeOf((*MockInventoryRepository)(nil).DeleteProductBySku), ctx, sku)
}

// GetProductBySku mocks base method.
func (m *MockInventoryRepository) GetProductBySku(ctx context.Context, sku int) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductBySku", ctx, sku)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductBySku indicates an expected call of GetProductBySku.
func (mr *MockInventoryRepositoryMockRecorder) GetProductBySku(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductBySku", reflect.TypeOf((*MockInventoryRepository)(nil).GetProductBySku), ctx, sku)
}

// GetProductByUpc mocks base method.
func (m *MockInventoryRepository) GetProductByUpc(ctx context.Context, upc string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByUpc", ctx, upc)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByUpc indicates an expected call of GetProductByUpc.
func (mr *MockInventoryRepositoryMockRecorder) GetProductByUpc(ctx, upc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByUpc", reflect.TypeOf((*MockInventoryRepository)(nil).GetProductByUpc), ctx, upc)
}

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// MockMerchandisingRepository is a mock of MerchandisingRepository interface.
type MockMerchandisingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchandisingRepositoryMockRecorder
	isgomock struct{}
}

// MockMerchandisingRepositoryMockRecorder is the mock recorder for MockMerchandisingRepository.
type MockMerchandisingRepositoryMockRecorder struct {
	mock *MockMerchandisingRepository
}

// NewMockMerchandisingRepository creates a new mock instance.
func NewMockMerchandisingRepository(ctrl *gomock.Controller) *MockMerchandisingRepository {
	mock := &MockMerchandisingRepository{ctrl: ctrl}
	mock.recorder = &MockMerchandisingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchandisingRepository) EXPECT() *MockMerchandisingRepositoryMockRecorder {
	return m.recorder
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionRepository) CreateSession(ctx context.Context, model models.CreateSessionRequest) (*models.CreateSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, model)
	ret0, _ := ret[0].(*models.CreateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepositoryMockRecorder) CreateSession(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepository)(nil).CreateSession), ctx, model)
}

// GetAllSessions mocks base method.
func (m *MockSessionRepository) GetAllSessions(ctx context.Context, limit, offset int) ([]models.GetAllSessions, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSessions", ctx, limit, offset)
	ret0, _ := ret[0].([]models.GetAllSessions)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllSessions indicates an expected call of GetAllSessions.
func (mr *MockSessionRepositoryMockRecorder) GetAllSessions(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSessions", reflect.TypeOf((*MockSessionRepository)(nil).GetAllSessions), ctx, limit, offset)
}

// GetSessionByAccessTokenHash mocks base method.
func (m *MockSessionRepository) GetSessionByAccessTokenHash(ctx context.Context, accessTokenHash string) (*models.GetSessionByHashedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByAccessTokenHash", ctx, accessTokenHash)
	ret0, _ := ret[0].(*models.GetSessionByHashedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByAccessTokenHash indicates an expected call of GetSessionByAccessTokenHash.
func (mr *MockSessionRepositoryMockRecorder) GetSessionByAccessTokenHash(ctx, accessTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByAccessTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionByAccessTokenHash), ctx, accessTokenHash)
}

// GetSessionById mocks base method.
func (m *MockSessionRepository) GetSessionById(ctx context.Context, id int) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionById", ctx, id)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionById indicates an expected call of GetSessionById.
func (mr *MockSessionRepositoryMockRecorder) GetSessionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionById", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionById), ctx, id)
}

// GetSessionByRefreshTokenHash mocks base method.
func (m *MockSessionRepository) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (*models.GetSessionByHashedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshTokenHash", ctx, refreshTokenHash)
	ret0, _ := ret[0].(*models.GetSessionByHashedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshTokenHash indicates an expected call of GetSessionByRefreshTokenHash.
func (mr *MockSessionRepositoryMockRecorder) GetSessionByRefreshTokenHash(ctx, refreshTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionByRefreshTokenHash), ctx, refreshTokenHash)
}

// TerminateExpiredSessions mocks base method.
func (m *MockSessionRepository) TerminateExpiredSessions(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateExpiredSessions", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TerminateExpiredSessions indicates an expected call of TerminateExpiredSessions.
func (mr *MockSessionRepositoryMockRecorder) TerminateExpiredSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateExpiredSessions", reflect.TypeOf((*MockSessionRepository)(nil).TerminateExpiredSessions), ctx)
}

// TerminateSessionByAccessTokenHash mocks base method.
func (m *MockSessionRepository) TerminateSessionByAccessTokenHash(ctx context.Context, accessTokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateSessionByAccessTokenHash", ctx, accessTokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateSessionByAccessTokenHash indicates an expected call of TerminateSessionByAccessTokenHash.
func (mr *MockSessionRepositoryMockRecorder) TerminateSessionByAccessTokenHash(ctx, accessTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateSessionByAccessTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).TerminateSessionByAccessTokenHash), ctx, accessTokenHash)
}

// TerminateSessionById mocks base method.
func (m *MockSessionRepository) TerminateSessionById(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateSessionById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateSessionById indicates an expected call of TerminateSessionById.
func (mr *MockSessionRepositoryMockRecorder) TerminateSessionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateSessionById", reflect.TypeOf((*MockSessionRepository)(nil).TerminateSessionById), ctx, id)
}

// UpdateAccessTokenHash mocks base method.
func (m *MockSessionRepository) UpdateAccessTokenHash(ctx context.Context, sessionId int, newAccessTokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessTokenHash", ctx, sessionId, newAccessTokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccessTokenHash indicates an expected call of UpdateAccessTokenHash.
func (mr *MockSessionRepositoryMockRecorder) UpdateAccessTokenHash(ctx, sessionId, newAccessTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).UpdateAccessTokenHash), ctx, sessionId, newAccessTokenHash)
}

// UpdateSessionExpiry mocks base method.
func (m *MockSessionRepository) UpdateSessionExpiry(ctx context.Context, sessionId int, newExpiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionExpiry", ctx, sessionId, newExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionExpiry indicates an expected call of UpdateSessionExpiry.
func (mr *MockSessionRepositoryMockRecorder) UpdateSessionExpiry(ctx, sessionId, newExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionExpiry", reflect.TypeOf((*MockSessionRepository)(nil).UpdateSessionExpiry), ctx, sessionId, newExpiresAt)
}
