// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces.go -destination=internal/service/mocks/mock_repositories.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "radius/internal/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockEmployeeRepository is a mock of EmployeeRepository interface.
type MockEmployeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeRepositoryMockRecorder
	isgomock struct{}
}

// MockEmployeeRepositoryMockRecorder is the mock recorder for MockEmployeeRepository.
type MockEmployeeRepositoryMockRecorder struct {
	mock *MockEmployeeRepository
}

// NewMockEmployeeRepository creates a new mock instance.
func NewMockEmployeeRepository(ctrl *gomock.Controller) *MockEmployeeRepository {
	mock := &MockEmployeeRepository{ctrl: ctrl}
	mock.recorder = &MockEmployeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployeeRepository) EXPECT() *MockEmployeeRepositoryMockRecorder {
	return m.recorder
}

// ActivateEmployeeById mocks base method.
func (m *MockEmployeeRepository) ActivateEmployeeById(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateEmployeeById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateEmployeeById indicates an expected call of ActivateEmployeeById.
func (mr *MockEmployeeRepositoryMockRecorder) ActivateEmployeeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateEmployeeById", reflect.TypeOf((*MockEmployeeRepository)(nil).ActivateEmployeeById), ctx, id)
}

// CreateEmployee mocks base method.
func (m *MockEmployeeRepository) CreateEmployee(ctx context.Context, model models.CreateEmployeeRow) (*models.CreateEmployeeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, model)
	ret0, _ := ret[0].(*models.CreateEmployeeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockEmployeeRepositoryMockRecorder) CreateEmployee(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockEmployeeRepository)(nil).CreateEmployee), ctx, model)
}

// GetAllEmployees mocks base method.
func (m *MockEmployeeRepository) GetAllEmployees(ctx context.Context, limit, offset int, storeId *int) ([]models.Employee, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEmployees", ctx, limit, offset, storeId)
	ret0, _ := ret[0].([]models.Employee)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllEmployees indicates an expected call of GetAllEmployees.
func (mr *MockEmployeeRepositoryMockRecorder) GetAllEmployees(ctx, limit, offset, storeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEmployees", reflect.TypeOf((*MockEmployeeRepository)(nil).GetAllEmployees), ctx, limit, offset, storeId)
}

// GetEmployeeByEmail mocks base method.
func (m *MockEmployeeRepository) GetEmployeeByEmail(ctx context.Context, email string) (*models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByEmail", ctx, email)
	ret0, _ := ret[0].(*models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByEmail indicates an expected call of GetEmployeeByEmail.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeeByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByEmail", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeeByEmail), ctx, email)
}

// GetEmployeeByEmailWithSession mocks base method.
func (m *MockEmployeeRepository) GetEmployeeByEmailWithSession(ctx context.Context, email string) (*models.GetEmployeeByEmailWithSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByEmailWithSession", ctx, email)
	ret0, _ := ret[0].(*models.GetEmployeeByEmailWithSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByEmailWithSession indicates an expected call of GetEmployeeByEmailWithSession.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeeByEmailWithSession(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByEmailWithSession", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeeByEmailWithSession), ctx, email)
}

// TerminateEmployeeById mocks base method.
func (m *MockEmployeeRepository) TerminateEmployeeById(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateEmployeeById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateEmployeeById indicates an expected call of TerminateEmployeeById.
func (mr *MockEmployeeRepositoryMockRecorder) TerminateEmployeeById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateEmployeeById", reflect.TypeOf((*MockEmployeeRepository)(nil).TerminateEmployeeById), ctx, id)
}

// UpdateEmployee mocks base method.
func (m *MockEmployeeRepository) UpdateEmployee(ctx context.Context, body models.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", ctx, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockEmployeeRepositoryMockRecorder) UpdateEmployee(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockEmployeeRepository)(nil).UpdateEmployee), ctx, body)
}

// MockStoreRepository is a mock of StoreRepository interface.
type MockStoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoreRepositoryMockRecorder
	isgomock struct{}
}

// MockStoreRepositoryMockRecorder is the mock recorder for MockStoreRepository.
type MockStoreRepositoryMockRecorder struct {
	mock *MockStoreRepository
}

// NewMockStoreRepository creates a new mock instance.
func NewMockStoreRepository(ctrl *gomock.Controller) *MockStoreRepository {
	mock := &MockStoreRepository{ctrl: ctrl}
	mock.recorder = &MockStoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreRepository) EXPECT() *MockStoreRepositoryMockRecorder {
	return m.recorder
}

// ActivateStore mocks base method.
func (m *MockStoreRepository) ActivateStore(ctx context.Context, storeId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateStore", ctx, storeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateStore indicates an expected call of ActivateStore.
func (mr *MockStoreRepositoryMockRecorder) ActivateStore(ctx, storeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateStore", reflect.TypeOf((*MockStoreRepository)(nil).ActivateStore), ctx, storeId)
}

// CreateStore mocks base method.
func (m *MockStoreRepository) CreateStore(ctx context.Context, body models.CreateStoreRequest) (*models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", ctx, body)
	ret0, _ := ret[0].(*models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockStoreRepositoryMockRecorder) CreateStore(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockStoreRepository)(nil).CreateStore), ctx, body)
}

// DeactivateStore mocks base method.
func (m *MockStoreRepository) DeactivateStore(ctx context.Context, storeId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateStore", ctx, storeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateStore indicates an expected call of DeactivateStore.
func (mr *MockStoreRepositoryMockRecorder) DeactivateStore(ctx, storeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateStore", reflect.TypeOf((*MockStoreRepository)(nil).DeactivateStore), ctx, storeId)
}

// GetAllStores mocks base method.
func (m *MockStoreRepository) GetAllStores(ctx context.Context, pageSize, pageNumber int) ([]models.Store, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStores", ctx, pageSize, pageNumber)
	ret0, _ := ret[0].([]models.Store)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllStores indicates an expected call of GetAllStores.
func (mr *MockStoreRepositoryMockRecorder) GetAllStores(ctx, pageSize, pageNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStores", reflect.TypeOf((*MockStoreRepository)(nil).GetAllStores), ctx, pageSize, pageNumber)
}

// GetStore mocks base method.
func (m *MockStoreRepository) GetStore(ctx context.Context, storeId int) (*models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", ctx, storeId)
	ret0, _ := ret[0].(*models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockStoreRepositoryMockRecorder) GetStore(ctx, storeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockStoreRepository)(nil).GetStore), ctx, storeId)
}

// UpdateStore mocks base method.
func (m *MockStoreRepository) UpdateStore(ctx context.Context, body models.UpdateStoreRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStore", ctx, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStore indicates an expected call of UpdateStore.
func (mr *MockStoreRepositoryMockRecorder) UpdateStore(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStore", reflect.TypeOf((*MockStoreRepository)(nil).UpdateStore), ctx, body)
}

// MockSalesRepository is a mock of SalesRepository interface.
type MockSalesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSalesRepositoryMockRecorder
	isgomock struct{}
}

// MockSalesRepositoryMockRecorder is the mock recorder for MockSalesRepository.
type MockSalesRepositoryMockRecorder struct {
	mock *MockSalesRepository
}

// NewMockSalesRepository creates a new mock instance.
func NewMockSalesRepository(ctrl *gomock.Controller) *MockSalesRepository {
	mock := &MockSalesRepository{ctrl: ctrl}
	mock.recorder = &MockSalesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSalesRepository) EXPECT() *MockSalesRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockSalesRepository) CreateTransaction(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateTransaction", ctx)
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockSalesRepositoryMockRecorder) CreateTransaction(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockSalesRepository)(nil).CreateTransaction), ctx)
}

// GetAllTransactions mocks base method.
func (m *MockSalesRepository) GetAllTransactions(ctx context.Context, limit, offset int, storeID *int) ([]models.Transaction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTransactions", ctx, limit, offset, storeID)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllTransactions indicates an expected call of GetAllTransactions.
func (mr *MockSalesRepositoryMockRecorder) GetAllTransactions(ctx, limit, offset, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTransactions", reflect.TypeOf((*MockSalesRepository)(nil).GetAllTransactions), ctx, limit, offset, storeID)
}

// GetProductTransactions mocks base method.
func (m *MockSalesRepository) GetProductTransactions(ctx context.Context, sku int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetProductTransactions", ctx, sku)
}

// GetProductTransactions indicates an expected call of GetProductTransactions.
func (mr *MockSalesRepositoryMockRecorder) GetProductTransactions(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductTransactions", reflect.TypeOf((*MockSalesRepository)(nil).GetProductTransactions), ctx, sku)
}

// GetTransactionByID mocks base method.
func (m *MockSalesRepository) GetTransactionByID(ctx context.Context, id int, storeID *int) (*models.Transaction, []models.TransactionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", ctx, id, storeID)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].([]models.TransactionItem)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockSalesRepositoryMockRecorder) GetTransactionByID(ctx, id, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockSalesRepository)(nil).GetTransactionByID), ctx, id, storeID)
}

// MockOrdersRepository is a mock of OrdersRepository interface.
type MockOrdersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersRepositoryMockRecorder
	isgomock struct{}
}

// MockOrdersRepositoryMockRecorder is the mock recorder for MockOrdersRepository.
type MockOrdersRepositoryMockRecorder struct {
	mock *MockOrdersRepository
}

// NewMockOrdersRepository creates a new mock instance.
func NewMockOrdersRepository(ctrl *gomock.Controller) *MockOrdersRepository {
	mock := &MockOrdersRepository{ctrl: ctrl}
	mock.recorder = &MockOrdersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepository) EXPECT() *MockOrdersRepositoryMockRecorder {
	return m.recorder
}

// GetAllOnlineOrders mocks base method.
func (m *MockOrdersRepository) GetAllOnlineOrders(ctx context.Context, limit, offset int, storeID *int, criteria models.OrderSearchCriteria) ([]models.OnlineOrder, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOnlineOrders", ctx, limit, offset, storeID, criteria)
	ret0, _ := ret[0].([]models.OnlineOrder)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllOnlineOrders indicates an expected call of GetAllOnlineOrders.
func (mr *MockOrdersRepositoryMockRecorder) GetAllOnlineOrders(ctx, limit, offset, storeID, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOnlineOrders", reflect.TypeOf((*MockOrdersRepository)(nil).GetAllOnlineOrders), ctx, limit, offset, storeID, criteria)
}

// GetOnlineOrderByID mocks base method.
func (m *MockOrdersRepository) GetOnlineOrderByID(ctx context.Context, id int, storeID *int) (*models.OnlineOrder, []models.OnlineOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnlineOrderByID", ctx, id, storeID)
	ret0, _ := ret[0].(*models.OnlineOrder)
	ret1, _ := ret[1].([]models.OnlineOrderItem)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOnlineOrderByID indicates an expected call of GetOnlineOrderByID.
func (mr *MockOrdersRepositoryMockRecorder) GetOnlineOrderByID(ctx, id, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnlineOrderByID", reflect.TypeOf((*MockOrdersRepository)(nil).GetOnlineOrderByID), ctx, id, storeID)
}

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// CheckLocationExists mocks base method.
func (m *MockInventoryRepository) CheckLocationExists(ctx context.Context, storeID int, locationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLocationExists", ctx, storeID, locationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLocationExists indicates an expected call of CheckLocationExists.
func (mr *MockInventoryRepositoryMockRecorder) CheckLocationExists(ctx, storeID, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLocationExists", reflect.TypeOf((*MockInventoryRepository)(nil).CheckLocationExists), ctx, storeID, locationID)
}

// CheckProductInLocation mocks base method.
func (m *MockInventoryRepository) CheckProductInLocation(ctx context.Context, storeID int, locationID string, productID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProductInLocation", ctx, storeID, locationID, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProductInLocation indicates an expected call of CheckProductInLocation.
func (mr *MockInventoryRepositoryMockRecorder) CheckProductInLocation(ctx, storeID, locationID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProductInLocation", reflect.TypeOf((*MockInventoryRepository)(nil).CheckProductInLocation), ctx, storeID, locationID, productID)
}

// CreateInventoryAdjustment mocks base method.
func (m *MockInventoryRepository) CreateInventoryAdjustment(ctx context.Context, adj models.InventoryAdjustment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInventoryAdjustment", ctx, adj)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInventoryAdjustment indicates an expected call of CreateInventoryAdjustment.
func (mr *MockInventoryRepositoryMockRecorder) CreateInventoryAdjustment(ctx, adj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInventoryAdjustment", reflect.TypeOf((*MockInventoryRepository)(nil).CreateInventoryAdjustment), ctx, adj)
}

// CreateMimsLocation mocks base method.
func (m *MockInventoryRepository) CreateMimsLocation(ctx context.Context, storeID int, locationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMimsLocation", ctx, storeID, locationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMimsLocation indicates an expected call of CreateMimsLocation.
func (mr *MockInventoryRepositoryMockRecorder) CreateMimsLocation(ctx, storeID, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMimsLocation", reflect.TypeOf((*MockInventoryRepository)(nil).CreateMimsLocation), ctx, storeID, locationID)
}

// GetInventoryByBarcode mocks base method.
func (m *MockInventoryRepository) GetInventoryByBarcode(ctx context.Context, storeID int, barcode string) (*models.MimsProductInventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventoryByBarcode", ctx, storeID, barcode)
	ret0, _ := ret[0].(*models.MimsProductInventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventoryByBarcode indicates an expected call of GetInventoryByBarcode.
func (mr *MockInventoryRepositoryMockRecorder) GetInventoryByBarcode(ctx, storeID, barcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventoryByBarcode", reflect.TypeOf((*MockInventoryRepository)(nil).GetInventoryByBarcode), ctx, storeID, barcode)
}

// GetPendingAdjustments mocks base method.
func (m *MockInventoryRepository) GetPendingAdjustments(ctx context.Context, storeID int) ([]models.PendingAdjustmentDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingAdjustments", ctx, storeID)
	ret0, _ := ret[0].([]models.PendingAdjustmentDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingAdjustments indicates an expected call of GetPendingAdjustments.
func (mr *MockInventoryRepositoryMockRecorder) GetPendingAdjustments(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingAdjustments", reflect.TypeOf((*MockInventoryRepository)(nil).GetPendingAdjustments), ctx, storeID)
}

// GetProductScreenDetails mocks base method.
func (m *MockInventoryRepository) GetProductScreenDetails(ctx context.Context, storeID, productID int) (*models.ProductScreenDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductScreenDetails", ctx, storeID, productID)
	ret0, _ := ret[0].(*models.ProductScreenDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductScreenDetails indicates an expected call of GetProductScreenDetails.
func (mr *MockInventoryRepositoryMockRecorder) GetProductScreenDetails(ctx, storeID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductScreenDetails", reflect.TypeOf((*MockInventoryRepository)(nil).GetProductScreenDetails), ctx, storeID, productID)
}

// GetProductsByLocation mocks base method.
func (m *MockInventoryRepository) GetProductsByLocation(ctx context.Context, storeID int, locationID string) ([]models.MimsProductInventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByLocation", ctx, storeID, locationID)
	ret0, _ := ret[0].([]models.MimsProductInventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByLocation indicates an expected call of GetProductsByLocation.
func (mr *MockInventoryRepositoryMockRecorder) GetProductsByLocation(ctx, storeID, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByLocation", reflect.TypeOf((*MockInventoryRepository)(nil).GetProductsByLocation), ctx, storeID, locationID)
}

// IncrementInventoryQuantity mocks base method.
func (m *MockInventoryRepository) IncrementInventoryQuantity(ctx context.Context, storeID, productID, delta int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementInventoryQuantity", ctx, storeID, productID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementInventoryQuantity indicates an expected call of IncrementInventoryQuantity.
func (mr *MockInventoryRepositoryMockRecorder) IncrementInventoryQuantity(ctx, storeID, productID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementInventoryQuantity", reflect.TypeOf((*MockInventoryRepository)(nil).IncrementInventoryQuantity), ctx, storeID, productID, delta)
}

// LinkProductToLocation mocks base method.
func (m *MockInventoryRepository) LinkProductToLocation(ctx context.Context, storeID int, locationID string, productID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkProductToLocation", ctx, storeID, locationID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkProductToLocation indicates an expected call of LinkProductToLocation.
func (mr *MockInventoryRepositoryMockRecorder) LinkProductToLocation(ctx, storeID, locationID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkProductToLocation", reflect.TypeOf((*MockInventoryRepository)(nil).LinkProductToLocation), ctx, storeID, locationID, productID)
}

// LogScan mocks base method.
func (m *MockInventoryRepository) LogScan(ctx context.Context, log models.MimsScanLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogScan", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogScan indicates an expected call of LogScan.
func (mr *MockInventoryRepositoryMockRecorder) LogScan(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogScan", reflect.TypeOf((*MockInventoryRepository)(nil).LogScan), ctx, log)
}

// ReviewAdjustments mocks base method.
func (m *MockInventoryRepository) ReviewAdjustments(ctx context.Context, storeID, reviewerID int, reviews []models.ReviewAdjustmentItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewAdjustments", ctx, storeID, reviewerID, reviews)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReviewAdjustments indicates an expected call of ReviewAdjustments.
func (mr *MockInventoryRepositoryMockRecorder) ReviewAdjustments(ctx, storeID, reviewerID, reviews any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewAdjustments", reflect.TypeOf((*MockInventoryRepository)(nil).ReviewAdjustments), ctx, storeID, reviewerID, reviews)
}

// SyncLocations mocks base method.
func (m *MockInventoryRepository) SyncLocations(ctx context.Context, storeID, inventoryID int, locations []models.MimsLocationItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncLocations", ctx, storeID, inventoryID, locations)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncLocations indicates an expected call of SyncLocations.
func (mr *MockInventoryRepositoryMockRecorder) SyncLocations(ctx, storeID, inventoryID, locations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncLocations", reflect.TypeOf((*MockInventoryRepository)(nil).SyncLocations), ctx, storeID, inventoryID, locations)
}

// UpdateInventoryQuantity mocks base method.
func (m *MockInventoryRepository) UpdateInventoryQuantity(ctx context.Context, storeID, productID, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventoryQuantity", ctx, storeID, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInventoryQuantity indicates an expected call of UpdateInventoryQuantity.
func (mr *MockInventoryRepositoryMockRecorder) UpdateInventoryQuantity(ctx, storeID, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventoryQuantity", reflect.TypeOf((*MockInventoryRepository)(nil).UpdateInventoryQuantity), ctx, storeID, productID, quantity)
}

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// GetProductByID mocks base method.
func (m *MockProductRepository) GetProductByID(ctx context.Context, id int) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductRepositoryMockRecorder) GetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductRepository)(nil).GetProductByID), ctx, id)
}

// GetProductByBarcode mocks base method.
func (m *MockProductRepository) GetProductByBarcode(ctx context.Context, barcode string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByBarcode", ctx, barcode)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByBarcode indicates an expected call of GetProductByBarcode.
func (mr *MockProductRepositoryMockRecorder) GetProductByBarcode(ctx, barcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByBarcode", reflect.TypeOf((*MockProductRepository)(nil).GetProductByBarcode), ctx, barcode)
}

// SearchProducts mocks base method.
func (m *MockProductRepository) SearchProducts(ctx context.Context, query string, categoryID *int, brand *string, isActive *bool, unitOfMeasure *string, limit, offset int) ([]models.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProducts", ctx, query, categoryID, brand, isActive, unitOfMeasure, limit, offset)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchProducts indicates an expected call of SearchProducts.
func (mr *MockProductRepositoryMockRecorder) SearchProducts(ctx, query, categoryID, brand, isActive, unitOfMeasure, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProducts", reflect.TypeOf((*MockProductRepository)(nil).SearchProducts), ctx, query, categoryID, brand, isActive, unitOfMeasure, limit, offset)
}

// MockCategoryRepository is a mock of CategoryRepository interface.
type MockCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockCategoryRepositoryMockRecorder is the mock recorder for MockCategoryRepository.
type MockCategoryRepositoryMockRecorder struct {
	mock *MockCategoryRepository
}

// NewMockCategoryRepository creates a new mock instance.
func NewMockCategoryRepository(ctrl *gomock.Controller) *MockCategoryRepository {
	mock := &MockCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepository) EXPECT() *MockCategoryRepositoryMockRecorder {
	return m.recorder
}

// GetAllCategories mocks base method.
func (m *MockCategoryRepository) GetAllCategories(ctx context.Context) ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories", ctx)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockCategoryRepositoryMockRecorder) GetAllCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockCategoryRepository)(nil).GetAllCategories), ctx)
}

// GetDistinctBrands mocks base method.
func (m *MockCategoryRepository) GetDistinctBrands(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctBrands", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctBrands indicates an expected call of GetDistinctBrands.
func (mr *MockCategoryRepositoryMockRecorder) GetDistinctBrands(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctBrands", reflect.TypeOf((*MockCategoryRepository)(nil).GetDistinctBrands), ctx)
}

// MockMerchandisingRepository is a mock of MerchandisingRepository interface.
type MockMerchandisingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchandisingRepositoryMockRecorder
	isgomock struct{}
}

// MockMerchandisingRepositoryMockRecorder is the mock recorder for MockMerchandisingRepository.
type MockMerchandisingRepositoryMockRecorder struct {
	mock *MockMerchandisingRepository
}

// NewMockMerchandisingRepository creates a new mock instance.
func NewMockMerchandisingRepository(ctrl *gomock.Controller) *MockMerchandisingRepository {
	mock := &MockMerchandisingRepository{ctrl: ctrl}
	mock.recorder = &MockMerchandisingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchandisingRepository) EXPECT() *MockMerchandisingRepositoryMockRecorder {
	return m.recorder
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionRepository) CreateSession(ctx context.Context, model models.CreateSessionRequest) (*models.CreateSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, model)
	ret0, _ := ret[0].(*models.CreateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepositoryMockRecorder) CreateSession(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepository)(nil).CreateSession), ctx, model)
}

// GetAllSessions mocks base method.
func (m *MockSessionRepository) GetAllSessions(ctx context.Context, limit, offset int) ([]models.GetAllSessions, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSessions", ctx, limit, offset)
	ret0, _ := ret[0].([]models.GetAllSessions)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllSessions indicates an expected call of GetAllSessions.
func (mr *MockSessionRepositoryMockRecorder) GetAllSessions(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSessions", reflect.TypeOf((*MockSessionRepository)(nil).GetAllSessions), ctx, limit, offset)
}

// GetSessionByAccessTokenHash mocks base method.
func (m *MockSessionRepository) GetSessionByAccessTokenHash(ctx context.Context, accessTokenHash string) (*models.GetSessionByHashedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByAccessTokenHash", ctx, accessTokenHash)
	ret0, _ := ret[0].(*models.GetSessionByHashedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByAccessTokenHash indicates an expected call of GetSessionByAccessTokenHash.
func (mr *MockSessionRepositoryMockRecorder) GetSessionByAccessTokenHash(ctx, accessTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByAccessTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionByAccessTokenHash), ctx, accessTokenHash)
}

// GetSessionById mocks base method.
func (m *MockSessionRepository) GetSessionById(ctx context.Context, id int) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionById", ctx, id)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionById indicates an expected call of GetSessionById.
func (mr *MockSessionRepositoryMockRecorder) GetSessionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionById", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionById), ctx, id)
}

// GetSessionByRefreshTokenHash mocks base method.
func (m *MockSessionRepository) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (*models.GetSessionByHashedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshTokenHash", ctx, refreshTokenHash)
	ret0, _ := ret[0].(*models.GetSessionByHashedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshTokenHash indicates an expected call of GetSessionByRefreshTokenHash.
func (mr *MockSessionRepositoryMockRecorder) GetSessionByRefreshTokenHash(ctx, refreshTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionByRefreshTokenHash), ctx, refreshTokenHash)
}

// TerminateExpiredSessions mocks base method.
func (m *MockSessionRepository) TerminateExpiredSessions(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateExpiredSessions", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TerminateExpiredSessions indicates an expected call of TerminateExpiredSessions.
func (mr *MockSessionRepositoryMockRecorder) TerminateExpiredSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateExpiredSessions", reflect.TypeOf((*MockSessionRepository)(nil).TerminateExpiredSessions), ctx)
}

// TerminateSessionByAccessTokenHash mocks base method.
func (m *MockSessionRepository) TerminateSessionByAccessTokenHash(ctx context.Context, accessTokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateSessionByAccessTokenHash", ctx, accessTokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateSessionByAccessTokenHash indicates an expected call of TerminateSessionByAccessTokenHash.
func (mr *MockSessionRepositoryMockRecorder) TerminateSessionByAccessTokenHash(ctx, accessTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateSessionByAccessTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).TerminateSessionByAccessTokenHash), ctx, accessTokenHash)
}

// TerminateSessionById mocks base method.
func (m *MockSessionRepository) TerminateSessionById(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateSessionById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateSessionById indicates an expected call of TerminateSessionById.
func (mr *MockSessionRepositoryMockRecorder) TerminateSessionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateSessionById", reflect.TypeOf((*MockSessionRepository)(nil).TerminateSessionById), ctx, id)
}

// UpdateAccessTokenHash mocks base method.
func (m *MockSessionRepository) UpdateAccessTokenHash(ctx context.Context, sessionId int, newAccessTokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessTokenHash", ctx, sessionId, newAccessTokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccessTokenHash indicates an expected call of UpdateAccessTokenHash.
func (mr *MockSessionRepositoryMockRecorder) UpdateAccessTokenHash(ctx, sessionId, newAccessTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).UpdateAccessTokenHash), ctx, sessionId, newAccessTokenHash)
}

// UpdateSessionExpiry mocks base method.
func (m *MockSessionRepository) UpdateSessionExpiry(ctx context.Context, sessionId int, newExpiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionExpiry", ctx, sessionId, newExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionExpiry indicates an expected call of UpdateSessionExpiry.
func (mr *MockSessionRepositoryMockRecorder) UpdateSessionExpiry(ctx, sessionId, newExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionExpiry", reflect.TypeOf((*MockSessionRepository)(nil).UpdateSessionExpiry), ctx, sessionId, newExpiresAt)
}

// MockReceivingRepository is a mock of ReceivingRepository interface.
type MockReceivingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReceivingRepositoryMockRecorder
	isgomock struct{}
}

// MockReceivingRepositoryMockRecorder is the mock recorder for MockReceivingRepository.
type MockReceivingRepositoryMockRecorder struct {
	mock *MockReceivingRepository
}

// NewMockReceivingRepository creates a new mock instance.
func NewMockReceivingRepository(ctrl *gomock.Controller) *MockReceivingRepository {
	mock := &MockReceivingRepository{ctrl: ctrl}
	mock.recorder = &MockReceivingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceivingRepository) EXPECT() *MockReceivingRepositoryMockRecorder {
	return m.recorder
}

// CheckProductInPO mocks base method.
func (m *MockReceivingRepository) CheckProductInPO(ctx context.Context, poID int, barcode string) (*models.PurchaseOrderItemDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProductInPO", ctx, poID, barcode)
	ret0, _ := ret[0].(*models.PurchaseOrderItemDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProductInPO indicates an expected call of CheckProductInPO.
func (mr *MockReceivingRepositoryMockRecorder) CheckProductInPO(ctx, poID, barcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProductInPO", reflect.TypeOf((*MockReceivingRepository)(nil).CheckProductInPO), ctx, poID, barcode)
}

// CheckProductInTransfer mocks base method.
func (m *MockReceivingRepository) CheckProductInTransfer(ctx context.Context, transferID int, barcode string) (*models.StockTransferItemDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProductInTransfer", ctx, transferID, barcode)
	ret0, _ := ret[0].(*models.StockTransferItemDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProductInTransfer indicates an expected call of CheckProductInTransfer.
func (mr *MockReceivingRepositoryMockRecorder) CheckProductInTransfer(ctx, transferID, barcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProductInTransfer", reflect.TypeOf((*MockReceivingRepository)(nil).CheckProductInTransfer), ctx, transferID, barcode)
}

// GetPurchaseOrderDetail mocks base method.
func (m *MockReceivingRepository) GetPurchaseOrderDetail(ctx context.Context, poID int) (*models.PurchaseOrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseOrderDetail", ctx, poID)
	ret0, _ := ret[0].(*models.PurchaseOrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseOrderDetail indicates an expected call of GetPurchaseOrderDetail.
func (mr *MockReceivingRepositoryMockRecorder) GetPurchaseOrderDetail(ctx, poID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseOrderDetail", reflect.TypeOf((*MockReceivingRepository)(nil).GetPurchaseOrderDetail), ctx, poID)
}

// GetPurchaseOrders mocks base method.
func (m *MockReceivingRepository) GetPurchaseOrders(ctx context.Context, storeID *int) ([]models.PurchaseOrderSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseOrders", ctx, storeID)
	ret0, _ := ret[0].([]models.PurchaseOrderSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseOrders indicates an expected call of GetPurchaseOrders.
func (mr *MockReceivingRepositoryMockRecorder) GetPurchaseOrders(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseOrders", reflect.TypeOf((*MockReceivingRepository)(nil).GetPurchaseOrders), ctx, storeID)
}

// GetStockTransferDetail mocks base method.
func (m *MockReceivingRepository) GetStockTransferDetail(ctx context.Context, transferID int) (*models.StockTransferDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockTransferDetail", ctx, transferID)
	ret0, _ := ret[0].(*models.StockTransferDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockTransferDetail indicates an expected call of GetStockTransferDetail.
func (mr *MockReceivingRepositoryMockRecorder) GetStockTransferDetail(ctx, transferID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockTransferDetail", reflect.TypeOf((*MockReceivingRepository)(nil).GetStockTransferDetail), ctx, transferID)
}

// GetStockTransfers mocks base method.
func (m *MockReceivingRepository) GetStockTransfers(ctx context.Context, storeID *int) ([]models.StockTransferSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockTransfers", ctx, storeID)
	ret0, _ := ret[0].([]models.StockTransferSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockTransfers indicates an expected call of GetStockTransfers.
func (mr *MockReceivingRepositoryMockRecorder) GetStockTransfers(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockTransfers", reflect.TypeOf((*MockReceivingRepository)(nil).GetStockTransfers), ctx, storeID)
}

// QuickReceiveTransfer mocks base method.
func (m *MockReceivingRepository) QuickReceiveTransfer(ctx context.Context, storeID, transferID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuickReceiveTransfer", ctx, storeID, transferID)
	ret0, _ := ret[0].(error)
	return ret0
}

// QuickReceiveTransfer indicates an expected call of QuickReceiveTransfer.
func (mr *MockReceivingRepositoryMockRecorder) QuickReceiveTransfer(ctx, storeID, transferID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuickReceiveTransfer", reflect.TypeOf((*MockReceivingRepository)(nil).QuickReceiveTransfer), ctx, storeID, transferID)
}

// ReceiveLPR mocks base method.
func (m *MockReceivingRepository) ReceiveLPR(ctx context.Context, storeID, poID int, lprBarcode string, employeeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveLPR", ctx, storeID, poID, lprBarcode, employeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReceiveLPR indicates an expected call of ReceiveLPR.
func (mr *MockReceivingRepositoryMockRecorder) ReceiveLPR(ctx, storeID, poID, lprBarcode, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveLPR", reflect.TypeOf((*MockReceivingRepository)(nil).ReceiveLPR), ctx, storeID, poID, lprBarcode, employeeID)
}

// ReceivePOItems mocks base method.
func (m *MockReceivingRepository) ReceivePOItems(ctx context.Context, storeID, poID int, items []models.ReceivePOItemEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceivePOItems", ctx, storeID, poID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReceivePOItems indicates an expected call of ReceivePOItems.
func (mr *MockReceivingRepositoryMockRecorder) ReceivePOItems(ctx, storeID, poID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceivePOItems", reflect.TypeOf((*MockReceivingRepository)(nil).ReceivePOItems), ctx, storeID, poID, items)
}

// ReceiveTransferItems mocks base method.
func (m *MockReceivingRepository) ReceiveTransferItems(ctx context.Context, storeID, transferID int, items []models.ReceiveTransferItemEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveTransferItems", ctx, storeID, transferID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReceiveTransferItems indicates an expected call of ReceiveTransferItems.
func (mr *MockReceivingRepositoryMockRecorder) ReceiveTransferItems(ctx, storeID, transferID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveTransferItems", reflect.TypeOf((*MockReceivingRepository)(nil).ReceiveTransferItems), ctx, storeID, transferID, items)
}
